name: Bug report
description: 'Report reproducible bugs: include steps, logs, and environment details.'
title: 'Bug: '
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the impact?
      options:
        - blocker
        - high
        - medium
        - low
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgently should this be addressed?
      options:
        - P0 (urgent)
        - P1 (high)
        - P2 (normal)
        - P3 (low)

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise one-line summary of the bug.
      placeholder: A concise one-line summary.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide exact steps, including commands and inputs.
      placeholder: |
        1.
        2.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe the behavior you expected.
      placeholder: Describe the behavior you expected.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: Describe the observed behavior.
      placeholder: Describe the observed behavior.
    validations:
      required: true

  - type: textarea
    id: reproducible_example
    attributes:
      label: Reproducible example / minimal test case
      description: Provide a minimal code snippet, dataset, or commands to reproduce.
      placeholder: |
        # commands to reproduce
      render: shell

  - type: textarea
    id: logs_stack_traces
    attributes:
      label: Logs / Stack traces
      description: Paste relevant logs or stack traces.
      placeholder: |
        # logs or stack traces
      render: text

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide environment details.
      value: |
        - Project version / branch / commit:
        - OS:
        - Runtime/tooling versions:
    validations:
      required: true
