name: Documentation Request
description: Request corrections or additions to the documentation.
title: '[docs]: '
labels: ['documentation', 'triage']
body:
  - type: markdown
    attributes:
      value: Thank you for helping us improve our documentation!
  - type: textarea
    id: current-state
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (if applicable)
      placeholder: Please provide a link or quote from the current documentation
    validations:
      required: false
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: What changes would you like to see?
      placeholder: Describe your suggested improvements or additions in detail
    validations:
      required: true
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs to be updated?
      options:
        - API Reference
        - User Guide
        - Tutorial
        - README
        - Code Comments
        - Other
    validations:
      required: true
  - type: input
    id: affected-pages
    attributes:
      label: Affected Pages/Files
      description: Which documentation pages or files need to be updated?
      placeholder: e.g., /docs/api.md, README.md
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or examples that would help us understand your request
      placeholder: Include any relevant examples, screenshots, or additional context
