[package]
name = "name"
version = "1.0.0-alpha.1"
edition = "2024"
description = "Description of the project"
publish = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
log = { version = "0.4.29", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
ctrlc = { version = "3.5.2", features = ["termination"] }
config = "0.15.25"
fern = { version = "0.7.1", features = ["colored", "date-based"] }
directories = "6.0.0"
toml = "1.1.2"

[lints.rust]
unsafe_code = "forbid"
invalid_reference_casting="forbid"

[lints.clippy]
excessive-nesting = "forbid"
too-many-lines = "forbid"
